s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-1-4-hypershift-oadp-plugin|registry.redhat.io/oadp/oadp-hypershift-velero-plugin-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-hypershift-oadp-plugin-oadp-1-4|registry.redhat.io/oadp/oadp-hypershift-velero-plugin-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-1-4-kubevirt-velero-plugin|registry.redhat.io/oadp/oadp-kubevirt-velero-plugin-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-kubevirt-velero-plugin-oadp-1-4|registry.redhat.io/oadp/oadp-kubevirt-velero-plugin-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-1-4-must-gather|registry.redhat.io/oadp/oadp-mustgather-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-must-gather-oadp-1-4|registry.redhat.io/oadp/oadp-mustgather-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-1-4-oadp-non-admin|registry.redhat.io/oadp/oadp-non-admin-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-oadp-non-admin-oadp-1-4|registry.redhat.io/oadp/oadp-non-admin-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-1-4-openshift-velero-plugin|registry.redhat.io/oadp/oadp-velero-plugin-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-openshift-velero-plugin-oadp-1-4|registry.redhat.io/oadp/oadp-velero-plugin-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-1-4-operator|registry.redhat.io/oadp/oadp-rhel9-operator|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-operator-oadp-1-4|registry.redhat.io/oadp/oadp-rhel9-operator|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-1-4-velero|registry.redhat.io/oadp/oadp-velero-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-velero-oadp-1-4|registry.redhat.io/oadp/oadp-velero-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-1-4-velero-plugin-for-aws|registry.redhat.io/oadp/oadp-velero-plugin-for-aws-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-velero-plugin-for-aws-oadp-1-4|registry.redhat.io/oadp/oadp-velero-plugin-for-aws-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-1-4-velero-plugin-for-gcp|registry.redhat.io/oadp/oadp-velero-plugin-for-gcp-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-velero-plugin-for-gcp-oadp-1-4|registry.redhat.io/oadp/oadp-velero-plugin-for-gcp-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-1-4-velero-plugin-for-legacy-aws|registry.redhat.io/oadp/oadp-velero-plugin-for-legacy-aws-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-velero-plugin-for-legacy-aws-oadp-1-4|registry.redhat.io/oadp/oadp-velero-plugin-for-legacy-aws-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-1-4-velero-plugin-for-microsoft-azure|registry.redhat.io/oadp/oadp-velero-plugin-for-microsoft-azure-rhel9|g
s|quay.io/redhat-user-workloads/ocp-art-tenant/oadp-velero-plugin-for-microsoft-azure-oadp-1-4|registry.redhat.io/oadp/oadp-velero-plugin-for-microsoft-azure-rhel9|g
